apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  labels:
    {{- include "cluster-secrets.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.mountPath | quote }}
          role: {{ .Values.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.auth.serviceAccountName }}
            namespace: {{ .Release.Namespace }}
            audiences:
              {{- toYaml .Values.vault.auth.audiences | nindent 14 }}
