{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "cluster-secrets.labels" $ | nindent 4 }}
spec:
  externalSecretName: {{ default .name .externalSecretName }}
  refreshTime: {{ $.Values.clusterExternalSecrets.refreshTime | quote }}
  {{- with .namespaces }}
  namespaces:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .namespaceSelectors }}
  namespaceSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  externalSecretSpec:
    refreshInterval: {{ default $.Values.clusterExternalSecrets.defaultRefreshInterval .refreshInterval | quote }}
    secretStoreRef:
      name: {{ $.Values.clusterSecretStore.name }}
      kind: ClusterSecretStore
    target:
      name: {{ .name }}
      creationPolicy: Owner
      deletionPolicy: Retain
      {{- if .dockerConfigJson }}
      template:
        type: kubernetes.io/dockerconfigjson
        engineVersion: v2
        data:
          .dockerconfigjson: '{{ include "cluster-secrets.dockerconfigjson" $ }}'
      {{- else if .targetTemplate }}
      template:
        {{- toYaml .targetTemplate | nindent 8 }}
      {{- end }}
    data:
      {{- range .data }}
      - secretKey: {{ .secretKey }}
        remoteRef:
          key: {{ .remoteRef.key | quote }}
          property: {{ .remoteRef.property | quote }}
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
      {{- end }}
{{- end }}
