apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.auth.serviceAccountName }}
  labels:
    {{- include "cluster-secrets.labels" . | nindent 4 }}
automountServiceAccountToken: false
