apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - root-application.yaml
  - platforms/external-secrets/application.yaml
  - platforms/vault/application.yaml
  - platforms/nginx-ingress/application.yaml
  - platforms/cloudflared/application.yaml
  - platforms/tailscale/application.yaml
  - platforms/argocd/config/application.yaml
  - apps/gitea/application.yaml
  - apps/homepage/application.yaml
  - apps/wiki/application.yaml
