apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "birthday.fullname" . }}
  labels:
    {{- include "birthday.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "static/index.html").AsConfig | nindent 2 }}
  {{- (.Files.Glob "nginx/default.conf").AsConfig | nindent 2 }}
