apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitea.fullname" . }}-config
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
data:
  ROOT_URL: {{ .Values.gitea.rootUrl | quote }}
  DB_HOST: {{ .Values.gitea.database.host | quote }}
