apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-secrets
  namespace: argocd

spec:
  project: default

  source:
    repoURL: {{ .Values.repoURL }}
    chart: external-secrets
    targetRevision: {{ .Values.chart.version }}

    helm:
      values: |
        installCRDs: true

        replicaCount: 1

        webhook:
          create: true
          replicaCount: 1

        certController:
          create: true
          replicaCount: 1

        leaderElect: true

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}

  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.prune }}
      selfHeal: {{ .Values.syncPolicy.selfHeal }}

    syncOptions:
      - CreateNamespace=true
