apiVersion: v2
name: immich-homeserver
description: Immich deployment for the homeserver cluster
type: application
version: 0.1.0
appVersion: "v3.1.0"
dependencies:
  - name: immich
    version: "0.13.1"
    repository: oci://ghcr.io/immich-app/immich-charts
