{{- if .Values.externalSecret.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecret.auth.serviceAccountName }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStore.name }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecret.secretStore.server | quote }}
      path: {{ .Values.externalSecret.secretStore.path | quote }}
      version: {{ .Values.externalSecret.secretStore.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecret.auth.mountPath | quote }}
          role: {{ .Values.externalSecret.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.externalSecret.auth.serviceAccountName }}
            audiences:
              {{- toYaml .Values.externalSecret.auth.audiences | nindent 14 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.tunnelToken.existingSecret }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.tunnelToken.existingSecret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .Values.tunnelToken.key }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        property: {{ .Values.externalSecret.remoteRef.property | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
