apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich-platform.libraryClaimName" . }}
  labels:
    {{- include "immich-platform.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.libraryPersistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.libraryPersistence.size }}
