{{- if .Values.library.create }}
{{- if .Values.library.staticHostPath.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.library.staticHostPath.persistentVolumeName }}
  labels:
    {{- include "immich-homeserver.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  capacity:
    storage: {{ .Values.library.staticHostPath.size }}
  accessModes:
    {{- toYaml .Values.library.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.library.staticHostPath.storageClass | quote }}
  volumeMode: Filesystem
  hostPath:
    path: {{ .Values.library.staticHostPath.hostPath | quote }}
    type: Directory
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.library.claimName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "immich-homeserver.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    {{- toYaml .Values.library.accessModes | nindent 4 }}
  storageClassName: {{ .Values.library.storageClass | quote }}
  volumeMode: Filesystem
  {{- if .Values.library.staticHostPath.enabled }}
  volumeName: {{ .Values.library.staticHostPath.persistentVolumeName }}
  {{- else if and .Values.library.volumeName (ne .Values.library.volumeName "") }}
  volumeName: {{ .Values.library.volumeName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.library.size }}
{{- end }}
