apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:authenticated
  policy.csv: |
    # Stable GitHub user ID for github.com/KanNguyenKiet.
    g, 20751267, role:admin
