apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-vault-auth
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: argocd
          serviceAccountRef:
            name: argocd-vault-auth
            audiences:
              - vault
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-github-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientID
      remoteRef:
        key: homeserver/argocd
        property: githubClientID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: clientSecret
      remoteRef:
        key: homeserver/argocd
        property: githubClientSecret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
