replicaCount: 1

image:
  registryHost: git.huukiet.com
  repository: git.huukiet.com/ops/homeserver-wiki
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitea-registry

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: wiki.huukiet.com
  path: /
  pathType: Prefix
  tls: []

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretName: gitea-registry
  secretStore:
    name: wiki-vault-backend
    server: http://vault.vault.svc.cluster.local:8200
    path: kv
    version: v2
  auth:
    serviceAccountName: wiki-vault-auth
    mountPath: kubernetes
    role: wiki
    audiences:
      - vault
  remoteRef:
    key: homeserver/wiki
    registryUsernameProperty: registryUsername
    registryPasswordProperty: registryPassword

podSecurityContext:
  fsGroup: 101
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 10

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
