apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "woodpecker-homeserver.name" . }}
    app.kubernetes.io/part-of: woodpecker
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
